spring:
  application:
    name: auth

  r2dbc:
    url: r2dbc:postgresql://localhost:5435/users
    username: admin
    password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5435/users
    username: admin
    password: 1234
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml
server:
  port: 8083
logging:
  level:
#    io.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.spi: DEBUG

#    reactor: DEBUG
#    io.grpc: DEBUG